export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const FIND_ONE_PRODUCT_REQUEST = "FIND_ONE_PRODUCT_REQUEST";
export const FIND_ONE_PRODUCT_SUCCESS = "FIND_ONE_PRODUCT_SUCCESS";
export const FIND_ONE_PRODUCT_FAIL = "FIND_ONE_PRODUCT_FAIL";
